%YAML 1.2
---
resource_dir: /home/drago/PycharmProjects/bioengine/resources

ner:
  stanford_jar: /home/drago/PycharmProjects/bioengine/resources/libs/stanford-ner.jar
  stanford_ner_model: /home/drago/PycharmProjects/bioengine/resources/models/bio-ner-model.ser.gz
  genia_tagger: /home/drago/PycharmProjects/bioengine/resources/libs/geniatagger-3.0.2/geniatagger
  metamap: /home/drago/Downloads/public_mm

similarity_vector: /home/drago/PycharmProjects/bioengine/resources/vectors/PubMed-shuffle-win-30.bin

neo4j:
  uri: bolt://localhost:7687
  user: engine_user
  password: password

headers:
  'User-Agent': Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

entrez:
  base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?

wikipedia_pipeline:
  div:
    id:
      - toc
      - siteSub
      - contentSub
    class:
      - reflist
      - infobox
      - thumb tright
  table:
  script:
  a:
    class: mw-jump-link
  li:
    class: interlanguage-link
  h3:

pmc_pipeline:
  div:
    id:
      - rightcolumn
    class:
      - navlink-box
      - pmc-page-banner whole_rhythm
      - fm-sec half_rhythm no_top_margin
      - fig
      - ref-cit-blk half_rhythm
  h3:
  sup: