version: '3'
networks:
  bridge:

services:
  knowledge_graph:
    image: neo4j:3.5.2
    network_mode: bridge
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - /home/drago/neo4j:/data/databases/graph.db
      - /home/drago/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allowFormatMigration=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
    # privileged: true
  ontology_store:
    image: neo4j:3.5.2
    network_mode: bridge
    ports:
      - 11005:11005
      - 11006:11006
      - 11004:11004
    volumes:
      - /home/drago/ontology_store:/data/databases/graph.db
      - /home/drago/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_allowFormatMigration=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:11005
      - NEO4J_dbms_connector_https_listen__address=:11006
      - NEO4J_dbms_connector_bolt_listen__address=:11004
      - NEO4J_dbms_connector_bolt_advertised__address=:11004
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
    privileged: true

        