name: ontosemantics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.8
  - aiosignal=1.3.2
  - annotated-types=0.7.0
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - async-timeout=4.0.3
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fastobo=0.13.0
  - fonttools=4.58.1
  - fqdn=1.5.1
  - freetype=2.13.3
  - frozenlist=1.6.0
  - greenlet=3.2.2
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - langchain=0.3.25
  - langchain-core=0.3.63
  - langchain-text-splitters=0.3.8
  - langsmith=0.3.42
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.6
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.50.0
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.6
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - multidict=6.4.4
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.5.0
  - orjson=3.10.18
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.5
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - pronto=2.7.0
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - pystache=0.6.8
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlalchemy=2.0.41
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tenacity=9.1.2
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.22.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - asgiref==3.8.1
      - backoff==2.2.1
      - bcrypt==4.3.0
      - bioc==2.1
      - biolink-model==4.2.5
      - build==1.2.2.post1
      - cachetools==5.5.2
      - chromadb==1.0.12
      - click==8.2.1
      - coloredlogs==15.0.1
      - curies==0.7.10
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - distro==1.9.0
      - docopt==0.6.2
      - durationpy==0.10
      - fastapi==0.115.9
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fsspec==2025.5.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.72.1
      - hbreader==0.9.1
      - hf-xet==1.1.3
      - httptools==0.6.4
      - httpx-sse==0.4.0
      - huggingface-hub==0.32.4
      - humanfriendly==10.0
      - iniconfig==2.1.0
      - interchange==2021.0.4
      - intervaltree==3.1.0
      - json-flattener==0.1.9
      - jsonasobj2==1.0.4
      - jsonlines==4.0.0
      - kubernetes==32.0.1
      - langchain-community==0.3.24
      - linkml-runtime==1.9.3
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - oauthlib==3.2.2
      - onnxruntime==1.22.0
      - opentelemetry-api==1.34.0
      - opentelemetry-exporter-otlp-proto-common==1.34.0
      - opentelemetry-exporter-otlp-proto-grpc==1.34.0
      - opentelemetry-instrumentation==0.55b0
      - opentelemetry-instrumentation-asgi==0.55b0
      - opentelemetry-instrumentation-fastapi==0.55b0
      - opentelemetry-proto==1.34.0
      - opentelemetry-sdk==1.34.0
      - opentelemetry-semantic-conventions==0.55b0
      - opentelemetry-util-http==0.55b0
      - pansi==2024.11.0
      - path==17.1.0
      - pathspec==0.12.1
      - pluggy==1.6.0
      - posthog==4.2.0
      - prefixcommons==0.1.12
      - prefixmaps==0.2.6
      - protobuf==5.29.5
      - py2neo==2021.2.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-settings==2.9.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytest==8.4.0
      - pytest-logging==2015.11.4
      - python-dotenv==1.1.0
      - pytrie==0.4.0
      - rdflib==7.1.4
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - shellingham==1.5.4
      - sortedcontainers==2.4.0
      - starlette==0.45.3
      - stringcase==1.2.0
      - sympy==1.14.0
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - typer==0.16.0
      - typing-inspect==0.9.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
      - yamllint==1.37.1
