package:
  name: bioengine
  version: 0.1

source:
  git_url: ../

#build:
#  number: 0
#  entry_points:
#    - conda-build = conda_build.cli.main_build:main
#    - conda-convert = conda_build.cli.main_convert:main
#    - conda-debug = conda_build.cli.main_debug:main
#    - conda-develop = conda_build.cli.main_develop:main
#    - conda-index = conda_build.cli.main_index:main
#    - conda-inspect = conda_build.cli.main_inspect:main
#    - conda-metapackage = conda_build.cli.main_metapackage:main
#    - conda-render = conda_build.cli.main_render:main
#    - conda-skeleton = conda_build.cli.main_skeleton:main

outputs:
  - type: wheel
  - name: {{ PKG_NAME }}

about:
  home: https://github.com/mdrago98/bioengine
  license: BSD 3-clause
